import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "min-h-screen w-[100svw]")}>
        {children}
        {/* <script src="../node_module/flowbite/dist/flowbite.min.js"></script> */}
      </body>
    </html>
  );
}
